### PR TITLE
Build and publish to NPM on release

### PR DESCRIPTION
**Pull request by alancleary**
This PR adds a GitHub workflow that builds the web components package and publishes it to NPM when a release is tagged. Note that publishing to NPM won't succeed unless there's a repository secret called `NPM_TOKEN`. See the [GitHub docs](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) for details. I'll send an email to the group about how this token may be generated.

Since it's inconvenient to test this PR, check out [my fork](https://github.com/alancleary/web-components) where I prototyped this and [the end result on NPM](https://www.npmjs.com/package/@alancleary/web-components).

### CODE REVIEW

**Comment by adf-ncgr** [comment]
looks fine to me insofar as I see an npm package was generated.

**Review by adf-ncgr — APPROVED** [review]
it seems to have worked, that's good enough for me- note that I haven't actually tried to do anything with said package...

**Comment by sammyjava** [comment]
https://www.npmjs.com/~sammyjava

**Comment by sammyjava** [comment]
I like that we're publishing to NPM but I'm not sure how I'd use it in the way we use it, loading it in a Jekyll site, in which case I'd want to build the minified JS file.
```
shokin@morangie:~$ mkdir web-components-test
shokin@morangie:~$ cd web-components-test/
shokin@morangie:~/web-components-test$ npm i @alancleary/web-components

added 7 packages in 199ms
shokin@morangie:~/web-components-test$ npm run build
npm ERR! Missing script: "build"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shokin/.npm/_logs/2023-08-02T21_03_43_700Z-debug-0.log
shokin@morangie:~/web-components-test$ 
```

**Comment by alancleary** [comment]
@sammyjava The package includes the build artifacts instead of the source code. Here's the files of interest in the package:

* `@alancleary/web-components/lib/` contains the compiled `.js` files with corresponding `.d.ts` and `.d.ts.map` type files so you can use the web component code as a library in another JS/TS project.
* `@alancleary/web-components/dist/web-components.min.js` the bundled and minified file intended for using the web components via their HTML tags.

**Comment by sammyjava** [comment]
Got it. Works for me!

**Comment by sammyjava** [comment]
Whooops, must have hit the wrong button. Reopening.

**Comment by alancleary** [comment]
@sammyjava I'm assuming you didn't mean to close the PR. Reopening.

**Review by sammyjava — APPROVED** [review]

**Comment by sammyjava** [comment]
> @sammyjava I'm assuming you didn't mean to close the PR. Reopening.

I think I beat you by a half second. :)

**Comment by alancleary** [comment]
I've added an `NPM_TOKEN` secret to the web components repo so this should be good to go now. I'll put a placeholder readme for NPM and then tag a release.

**Pull request merged**
