### PR TITLE
include pan gene set in results columns of gene search

### PR DESCRIPTION
**Pull request by adf-ncgr**
depends on https://github.com/legumeinfo/graphql-server/pull/126
fixes an issue I thought existed but maybe was just discussed in a meeting

### CODE REVIEW

**Comment by adf-ncgr** [comment]
now that the graphql v1.3.0 release has been made, I believe this PR should be ready for review.

**Review by alancleary — CHANGES_REQUESTED** [review]
It seems to be working as intended. Please update the GraphQL code in `dev/lis-gene-search-with-linkouts.html` as well.

**Comment by adf-ncgr** [comment]
Yes, I had been thinking about changing that, but it wasn't clear to me what the status of this code is:
```
      // the linkout function to give to the linkout search component
      function getLinkouts(linkoutData){
          const domain = 'https://cicer.legumeinfo.org';
          // returns a function with a promise to be used by the linkout search component
          // to populate the simple table element
          return queryLinkouts(domain, linkoutData);
      }
```
AFAICT, there is no queryLinkouts function defined anywhere I can find, and I'm unsure what the intent is using that domain; @ctcncgr can you clarify this or should I just change this to use something that works?

**Comment by alancleary** [comment]
> Yes, I had been thinking about changing that, but it wasn't clear to me what the status of this code is:
> 
> ```
>       // the linkout function to give to the linkout search component
>       function getLinkouts(linkoutData){
>           const domain = 'https://cicer.legumeinfo.org';
>           // returns a function with a promise to be used by the linkout search component
>           // to populate the simple table element
>           return queryLinkouts(domain, linkoutData);
>       }
> ```
> 
> AFAICT, there is no queryLinkouts function defined anywhere I can find, and I'm unsure what the intent is using that domain; @ctcncgr can you clarify this or should I just change this to use something that works?

Not sure what code you're quoting here. I was asking you to just update the GraphQL query in the search example so the "pangene sets" column isn't empty when results are loaded...

**Comment by adf-ncgr** [comment]
Hmm, I seem to have some old cruft under dev that doesn't correspond to what's in the repo; the file you referenced `dev/lis-gene-search-with-linkouts.html` seems to be cruft not existing in the repo whereas `dev/examples/lis-gene-search-with-linkouts.html` seems to be what you really want me to change. I guess there must have been some restructuring at some point that is confusing us both, but let me know if you think I'm still off-base

**Comment by alancleary** [comment]
> Hmm, I seem to have some old cruft under dev that doesn't correspond to what's in the repo; the file you referenced `dev/lis-gene-search-with-linkouts.html` seems to be cruft not existing in the repo whereas `dev/examples/lis-gene-search-with-linkouts.html` seems to be what you really want me to change. I guess there must have been some restructuring at some point that is confusing us both, but let me know if you think I'm still off-base

Whoops. I meant to say `dev/examples/lis-gene-search-with-linkouts.html`. That's what I get for typing from memory. Sorry for the confusion!

**Comment by adf-ncgr** [comment]
OK, `dev/examples/lis-gene-search-with-linkouts.html` updated.

**Review by alancleary — APPROVED** [review]

**Comment by sammyjava** [comment]
I have to say I have found it confusing that we have an "example" under `dev/examples` while the rest of the "examples" are under `dev`. But I recall that we're going to move the stuff under `dev` elsewhere, anyway. 
```console
dev
├── core
│   ├── lis-form-wrapper-element.html
│   ├── lis-modal-element.html
│   ├── lis-pagination-element.html
│   └── lis-simple-table-element.html
├── examples
│   └── lis-gene-search-with-linkouts.html
├── graphql.js
├── lis-gene-search-element.html
├── lis-linkout-element.html
├── lis-publication-search-element.html
├── lis-qtl-search-element.html
├── lis-trait-association-search-element.html
├── lis-trait-search-element.html
└── README.md
```

**Comment by adf-ncgr** [comment]
glad I'm in good company on this confusion

**Comment by alancleary** [comment]
:mag_right: :violin:

**Pull request merged**
