### PR TITLE
Pangene Lookup Components

### PR DESCRIPTION
**Pull request by alancleary**
This PR adds a pangene lookup component and various changes to support the component, including:

* The form wrapper component now supports specifying which button to programmatically submit a form with
* The paginated search mixin has been separated into two mixins: a basic search mixin and a paginated search mixin that extends the search mixin. Note: this is a breaking change as pagination parameters are now passed to the search function as part of the form data object instead of as separate parameters
* The search mixin supports an optional download function that allows a component's data in its entirety (i.e. non-paginated) to be downloaded (downloads do not  update querystring parameters)

### CODE REVIEW

**Review by adf-ncgr — COMMENTED** [review]
is there anything in particular you think I ought to look at? Otherwise I will just approve the changes, trusting that you know what you're doing here.

**Comment by alancleary** [comment]
> is there anything in particular you think I ought to look at? Otherwise I will just approve the changes, trusting that you know what you're doing here.

Mostly just one last kick of the tires. While preparing this PR I found a bit of code that hadn't been committed which is supposedly necessary so one last sanity check would be nice to be sure nothing else has slipped by.

**Review by adf-ncgr — CHANGES_REQUESTED** [review]
One nitpick; can you change the verbiage for the case where the targeted annotations don't have any members in the pangeneset matched by the query gene? Currently given as "No matches found for identifier", we had discussed an alternative via email a while back. otherwise, seems to be working as I would expect.

**Comment by alancleary** [comment]
> One nitpick; can you change the verbiage for the case where the targeted annotations don't have any members in the pangeneset matched by the query gene? Currently given as "No matches found for identifier", we had discussed an alternative via email a while back. otherwise, seems to be working as I would expect.

Whoops, I forgot about that. In the email you suggested "no matching targets found in pangene set for gene x." How do you feel about the subtly different "no matching targets found in a pangene set for gene x"? The prior assumes each gene belongs to a single pangene set whereas the latter does not, which means that's one less thing to remember and fix if/when we end up having multiple pangene sets loaded simultaneously.

**Comment by adf-ncgr** [comment]
sorry, was busy with other things. I feel fine about your subtle verbiage change and in fact tested the component against a version of glycinemine that has two pangenesets loaded concurrently- it works just as expected.

**Comment by alancleary** [comment]
> sorry, was busy with other things. I feel fine about your subtle verbiage change and in fact tested the component against a version of glycinemine that has two pangenesets loaded concurrently- it works just as expected.

The future is now I guess. Note that this error will only trigger if no matches are in full the result set, so if a query gene belongs to two pangene sets but only has matches for one of them then the error will not be shown. This scenario and the error verbiage are actually handled outside of the component so this is the sort of thing that can be fixed in the future without having to roll a new release of the components library.

**Pull request merged**
