### PR TITLE
Replaced other instances of geneFamilyIdentifier.

### PR DESCRIPTION
**Pull request by sammyjava**
I cleaned up some other mentions of geneFamilyIdentifier, including the generated docs. Plus there was a new docs file missing from the repo: docs/classes/core_components.LisLoadingElement.html

I did test this, no problems.

### CODE REVIEW

**Review by alancleary — CHANGES_REQUESTED** [review]
The GraphQL server gene search parameter for gene families is [`geneFamilyIdentifier`](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/api/search-genes.ts#L19), so the only line that needed to change in dev/examples/lis-gene-search[-with-linkouts].html is:
```js
// before
const geneFamilyIdentifier = searchData['geneFamilyIdentifier'];
// after
const geneFamilyIdentifier = searchData['family'];
```

**Comment by sammyjava** [comment]
Yeah, I ended up ONLY using geneFamilyIdentifier for the graphql query and using family locally, I think it's a bit less confusing.

**Comment by sammyjava** [comment]
(That was in the second commit.)

**Review by alancleary — APPROVED** [review]
Ah, I see. Sorry I missed that. I'm pretty distracted this week. Thanks for your patience.

**Pull request merged**
