### PR TITLE
Optional examples for web components

### PR DESCRIPTION
**Pull request by That-Thing**
Added optional parameters to modify set examples in all of the web components.

Ex: `<lis-trait-association-search-element traitsExample="one" publicationExample="two" authorExample="three"></lis-trait-association-search-element>`

### CODE REVIEW

**Review by sammyjava — COMMENTED** [review]
I'm confused. The examples are hardcoded into the web component:
```
src/lis-trait-association-search-element.ts:  traitsExample: string = 'R8 full maturity';
```
Is that just a place-filler? How do I set my own example strings without touching the code in the repo? Like in a .env file. We don't want to touch the web component code, right?

**Comment by That-Thing** [comment]
> I'm confused. The examples are hardcoded into the web component

That's just the default value in case the examples aren't set. Setting the examples is done through HTML or JS. 
```html
<!-- set the example text via HTML -->
<lis-trait-association-search-element traitsExample="traits" publicationExample="some DOI" authorExample="A name"></lis-trait-association-search-element>
 
<!-- set the example text via JavaScript -->
<lis-trait-association-search-element id="trait-association-search"></lis-trait-association-search-element>

<script type="text/javascript">
// get the trait association search element
const searchElement = document.getElementById('trait-association-search');
// set the element's example text properties
searchElement.traitsExample = "more traits";
searchElement.publicationExample = "another DOI";
searchElement.authorExample = "Someone else";
```

**Comment by sammyjava** [comment]
> > I'm confused. The examples are hardcoded into the web component:
> > ```
> > src/lis-trait-association-search-element.ts:  traitsExample: string = 'R8 full maturity';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is that just a place-filler? How do I set my own example strings without touching the code in the repo? Like in a .env file. We don't want to touch the web component code, right?
> 
> Those class members have the `@property` decorator, meaning they can be set in the HTML as tag attributes or via JavaScript as element properties. The values being assigned are the default values, i.e. what will be used if the attributes/properties aren't set when the component is used.
> 
> I think it might be worth not providing any default text rather than genera-specific text.

Definitely. AND provide a usage example in `dev/lis-trait-association-search-element.html` so I know what to test!

**Comment by sammyjava** [comment]
So yeah, here's my update requests:
1. Remove defaults from the src code.
2. Place usage examples in dev/lis-trait-association-search-element.html for whatever genus you want.

**Comment by adf-ncgr** [comment]
Thanks for tackling this! Just for my clarification, is the idea that we will eventually make templates and have these properties filled in from _data/examples.yml (or whatever)? This was something we'd discussed in our last NCGR LIS standup meeting, so not expecting @That-Thing has it on his radar but guessing that this effectively lays the proper groundwork.

**Comment by That-Thing** [comment]
@sammyjava Removed defaults and added the parameters into the example components.

**Comment by alancleary** [comment]
> Thanks for tackling this! Just for my clarification, is the idea that we will eventually make templates and have these properties filled in from _data/examples.yml (or whatever)? This was something we'd discussed in our last NCGR LIS standup meeting, so not expecting @That-Thing has it on his radar but guessing that this effectively lays the proper groundwork.

This enables that functionality, yes. This PR, however, is the result soybase wanting to use their own genus-specific examples.

**Review by sammyjava — APPROVED** [review]
Works for me! Thanks!

**Comment by alancleary** [comment]
> Works for me! Thanks!

I would like to review this PR before it gets merged. @That-Thing please hold off on merging!

**Comment by alancleary** [comment]
I pushed a handful of commits to this PR. Most of them are related to TSDoc comments and the text in the `dev/` examples. I also added a "form input help text" component to the `core/` directory and updated all of the search components to use it because now that the help text behavior isn't static it aught to be encapsulated so it's consistent across all components.

I'm going to recuse myself from the review process because I now have code that needs to be reviewed. So I guess it's up to you  @sammyjava. Feel free to weight in as well @That-Thing since my changes don't perfectly preserve the functionality you implemented.

**Comment by That-Thing** [comment]
The needed functionality is there so I have no issues with the changes.

**Pull request merged**
