### PR TITLE
Version 1.0.0

### PR DESCRIPTION
**Pull request by alancleary**
At long last.

### CODE REVIEW

**Review by adf-ncgr — APPROVED** [review]
could this be a dream?!
thanks for all the hard work to get us here

**Review by ctcncgr — APPROVED** [review]
Looks good. Will merge this into the linting once its done.

**Comment by svengato** [comment]
Did you remove the 'package' script, as in `npm run package`?

**Comment by svengato** [comment]
Another typo on line 36 of `README.md`: should be 'lis-gene-search-element'.

`<lis-gene-searh-element></lis-gene-searh-element>`

**Comment by alancleary** [comment]
> Another typo on line 36 of `README.md`: should be 'lis-gene-search-element'.
> 
> `<lis-gene-searh-element></lis-gene-searh-element>`

Nice catch. I added a commit that corrects the typo.

> > Did you remove the 'package' script, as in npm run package?
> 
> It looks like it is 'bundle' now, and the output is `dist/web-components.min.js` instead of `dist/web-components.bundled.js`? (Not sure how I missed that, it was a few months ago!)

Correct. The `package` script has been replaced with `bundle`. These changes were made in the build-publish branch, which wasn't merged until yesterday, so it's not surprising you didn't notice until now ;)

**Comment by svengato** [comment]
> Correct. The package script has been replaced with bundle. These changes were made in the build-publish branch, which wasn't merged until yesterday, so it's not surprising you didn't notice until now ;)

That explains it!

I am seeing the message "This branch has conflicts that must be resolved" on this page, is there anything I need to do about that? Otherwise I am ready to approve this version.

**Review by sammyjava — CHANGES_REQUESTED** [review]
I'm getting:
```
Uncaught TypeError: modal is null
    onload http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:232
    EventHandlerNonNull* http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:230
lis-gene-search-with-linkouts.html:232:9
    onload http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:232
    (Async: EventHandlerNonNull)
    <anonymous> http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:230
```

**Comment by sammyjava** [comment]
That's happening on the main branch now as well. I wonder if a dependency update mangled something.

**Comment by alancleary** [comment]
> I'm getting:
> 
> ```
> Uncaught TypeError: modal is null
>     onload http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:232
>     EventHandlerNonNull* http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:230
> lis-gene-search-with-linkouts.html:232:9
>     onload http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:232
>     (Async: EventHandlerNonNull)
>     <anonymous> http://localhost:8000/dev/examples/lis-gene-search-with-linkouts.html:230
> ```

Good catch! Since the non-bundled compiled JS code got moved from the `dist/` directory to the `lib/` directory in the build-publish PR, the script paths needed to be updated in all of the `dev/**/*.html` files. Apparently I missed both linkout examples. This PR now includes a commit that fixes the paths.

**Review by sammyjava — APPROVED** [review]
Looks good! Although I guess we're going to merge the switch to tables into this to preserve the tag? Whatever. This works.

**Pull request merged**
