### PR TITLE
Add trait keyword search component

### PR DESCRIPTION
**Pull request by svengato**

### CODE REVIEW

**Review by alancleary — CHANGES_REQUESTED** [review]
The code looks good, although I have one minor change request:

You use camel-case for the element IDs in `dev/index.html`, e.g. `"geneSearch"`. In HTML it's standard practice to use kebab-case, e.g. `"gene-search"`. Please update the element IDs to use this convention.

**Comment by sammyjava** [comment]
I didn't know that's called "kebab-case".

**Review by alancleary — COMMENTED** [review]
Code looks good. I'll test it real quick and merge if nothing comes up.

**Review by alancleary — APPROVED** [review]
The trait web component is working as expected. Approved!

**Pull request merged**
