### PR TITLE
Enhanced gene search

### PR DESCRIPTION
**Pull request by alancleary**
This PR updates the gene search component to search and filter on a variety of fields. There are many supporting changes included as well, such as support for customizing the display of results in the paginated search component, support for subgroupings of querstring parameters triggering a search on load, updating the paginated search component to have an optional scroll target element, adding a loading component to provide a consistent UI element for conveying loading status, encapsulating alerts in a core component, and moving from loading linkouts via a microservice to loading linkouts via GraphQL.

### CODE REVIEW

**Review by sammyjava — CHANGES_REQUESTED** [review]
I'm not getting  **gene identifier** or **chromosome location** linked in the search results. Just bolded text.

Double-checked, I'm definitely on `gene-search2`.

Never mind, I forgot that it's under "examples" rather than the one in front. But still an update I think we need, another comment....

**Review by sammyjava — COMMENTED** [review]
I think we should link the full gene identifier, not the name. The name is missing in many cases. The identifier is what we're actually hitting, as well - name is not unique so it's better UX to show the specific gene+annotation you're hitting.

**Comment by alancleary** [comment]
@sammyjava I've pushed commits that bind the linkout modal to the gene identifier instead of the name and that make the gene search component display "no name" when a gene doesn't have a name so that the name parentheses aren't empty.

> Never mind, I forgot that it's under "examples" rather than the one in front. But still an update I think we need, another comment....

Can you confirm what you mean by this?

**Comment by sammyjava** [comment]
> @sammyjava I've pushed commits that bind the linkout modal to the gene identifier instead of the name and that make the gene search component display "no name" when a gene doesn't have a name so that the name parentheses aren't empty.
> 
> > Never mind, I forgot that it's under "examples" rather than the one in front. But still an update I think we need, another comment....
> 
> Can you confirm what you mean by this?

Oh, I was just looking at `dev/lis-gene-search-element.html` which doesn't have linkouts rather than `dev/examples/lis-gene-search-with-linkouts.html` which does, that's all, when I was thinking the genes and locations weren't linked.

**Comment by alancleary** [comment]
> Oh, I was just looking at dev/lis-gene-search-element.html which doesn't have linkouts rather than dev/examples/lis-gene-search-with-linkouts.html which does, that's all, when I was thinking the genes and locations weren't linked.

OK. Let me know if you want anything else changed. I'm aiming to have this merged by the end of the day so we can tag a release.

**Comment by sammyjava** [comment]
Gene linkout testing with cicar.ICC4958.gnm2.ann1.Ca_00001
- [ ] GCV - POST to https://gcv-microservices.lis.ncgr.org/lis/genes responds with 500 and payload "500 Internal Server Error Server got itself in trouble" 
- [x] LegumeMine
- [ ] Funnotate -- gene is not present in the tree! Should be be showing Funnotate link for genes that aren't in trees, @svengato and @adf-ncgr  ???

**Comment by sammyjava** [comment]
Gene location linkout testing with cicar.ICC4958.gnm2.ann1.Ca_00001
- [ ] GCV **empty page** with **large error in console** starting with `Ee@https://gcv.legumeinfo.org/gcv2/main.fbb371a5cac15b03.js:1:252853 noMatchError@https://gcv.legumeinfo.org/gcv2/main.fbb371a5cac15b03.js:1:455223" "ERROR Error: Uncaught (in promise): Error: NG04002` @alancleary 
- [ ] JBrowse2 **returns JSON in page** instead of a JBrowse2 @ctcncgr 

Again, broken linkouts need to be fixed before we show gene search to the LIS folks.

**Comment by sammyjava** [comment]
> > Oh, I was just looking at dev/lis-gene-search-element.html which doesn't have linkouts rather than dev/examples/lis-gene-search-with-linkouts.html which does, that's all, when I was thinking the genes and locations weren't linked.
> 
> OK. Let me know if you want anything else changed. I'm aiming to have this merged by the end of the day so we can tag a release.

I would have said "go ahead" until I found that the ONLY linkout that works is LegumeMine. If that's all upstream bugs, we can merge this and I'll start barking at people to fix those linkouts. But let's be sure we're not introducing any bugs in graphql-server or web-components.

**Review by sammyjava — APPROVED** [review]

**Comment by alancleary** [comment]
Thanks, @sammyjava. I did not test the linkout service beyond confirming that the GraphQL API was providing links for genes and locations as expected.

Regarding the GCV location link you provided: the issue is that the URL that came from the service is not correct. The service returned https://gcv.legumeinfo.org/tools/gcv/, but it should be https://gcv.legumeinfo.org/gcv2. As with Funnotate, the chromosome you selected isn't actually in GCV so even with the correct URL you won't get a result.

Anyway, as @adf-ncgr confirmed via email, this appears to be an issue with the linkout service so I'm going to go ahead and merge.

**Comment by adf-ncgr** [comment]
At the present time, all of the genomes/annotations return the same linkouts, but only LegumeMine should really be expected to house all of them. I would expect a test gene like glyma.Wm82.gnm2.ann1.Glyma.06G065000 to return linkouts that work for all targets. I can begin tweaking linkouts for specific genomes/annotations but will need to coordinate with Nathan to restart the service to pick up the changes. Is there a dev instance you can point me to? Or should I be firing one up locally (I'll have to refresh my memory on doing this).

FWIW, the behavior of the funnotate linkouts is expected (by me), in that it takes you to the tree for the family to which the gene has been assigned, even if the gene isn't actually included in the tree. Maybe the verbiage of linkouts should differentiate the two cases, but I think it is good to allow them to get to the standard tree (and maybe someday we'll give the option to automagically recompute the tree if the gene isn't in it, similar to what we do when linking to funnotate from the Intermine list analysis page for proteins/transcripts).

I know some genomes will need to point to genus-specific GCV instances instead of the main one, but I am a little confused about why it would be returning tools/gcv paths at this time. JBrowse2 behaviors are probably also my bad here. Many species don't have them set up yet although I would actually expect the one you used to work, so maybe I broke something on it.

**Comment by sammyjava** [comment]
Thanks, @alancleary your work is done here!

I have major issues with linkouts that take you to something that isn't what you were told you'd see, or is just plain broken, so I fear that have much more work to do on linkouts.

I'll move these linkout issues to the microservices repo where linkouts are housed and we'll take it from there.

**Pull request merged**
